AWSTemplateFormatVersion: "2010-09-09"
Description: Basic CloudFormation template for API Gateway with Lambda function, DynamoDB, and Cognito authentication

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyDynamoDBTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: "*"

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyLambdaFunction
      Handler: index.handler
      Runtime: python3.8
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref MyDynamoDBTable
      Timeout: 10
      Code:
        ZipFile: |
          import json
          import boto3
          import os
          from boto3.dynamodb.conditions import Key

          dynamodb = boto3.resource('dynamodb')
          table = dynamodb.Table(os.environ['TABLE_NAME'])

          def handler(event, context):
              try:
                  if event['httpMethod'] == 'GET':
                      response = table.scan()
                      return {
                          "statusCode": 200,
                          "body": json.dumps(response['Items'])
                      }
                  elif event['httpMethod'] == 'POST':
                      body = json.loads(event['body'])
                      item = {
                          'id': body['id'],
                          'username': body['username'],
                      }
                      table.put_item(Item=item)
                      return {
                          "statusCode": 200,
                          "body": json.dumps(item)
                      }
                  else:
                      return {
                          "statusCode": 400,
                          "body": json.dumps({"message": "Unsupported method"})
                      }
              except Exception as e:
                  return {
                      "statusCode": 500,
                      "body": json.dumps({"message": str(e)})
                  }

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MyLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*"
  
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyApiGateway
      EndpointConfiguration:
        Types:
          - REGIONAL

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: users
      RestApiId: !Ref ApiGateway

  ApiGatewayMethodGet:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations"

  ApiGatewayMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations"
  
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayMethodGet
      - ApiGatewayMethodPost
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Prout
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      KeyName: SaMarchePa
      ImageId: ami-0e54671bdf3c8ed8d  
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: EC2GT
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          sudo yum update -y

          sudo dnf install mariadb105-server -y
          sudo systemctl start mariadb
          sudo systemctl enable mariadb

          mysql -u root <<EOF
          CREATE DATABASE erp;
          CREATE USER 'erp_user'@'localhost' IDENTIFIED BY 'erp_pass';
          GRANT ALL PRIVILEGES ON erp.* TO 'erp_user'@'localhost';
          FLUSH PRIVILEGES;
          EOF

          sudo yum install git -y

          sudo amazon-linux-extras enable corretto
          
          sudo yum install maven -y

          git clone https://github.com/NeoOniX/AWS-ERP.git /home/ec2-user/erp-java-app
          cd /home/ec2-user/erp-java-app
          mvn clean install
          mvn package
          java -jar target/erp-0.0.1.jar &

          curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
          sudo yum install nodejs -y
          sudo npm install -g pm2

          git clone https://github.com/NeoOniX/AWS-ERP-Front.git /home/ec2-user/erp-nextjs-app
          cd /home/ec2-user/erp-nextjs-app
          sudo npm install
          sudo npm run build
          pm2 start "npm run start" --name "ERP-Front" --watch
          pm2 save

          sudo yum install firewalld -y
          sudo systemctl start firewalld
          sudo systemctl enable firewalld
          sudo firewall-cmd --add-port=22/tcp --permanent
          sudo firewall-cmd --add-port=3306/tcp --permanent
          sudo firewall-cmd --add-port=8080/tcp --permanent
          sudo firewall-cmd --add-port=3000/tcp --permanent
          sudo firewall-cmd --reload

Outputs:
  GatewayApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/users"